Repository AY2223S2-CS2113-T13-1/tp, pull requests merged in 2023-03, with the labels that each got.

#2 Update AboutUs
  docs/AboutUs.md
Labels: documentation

#27 Add AccountList and Account class
  src/main/java/seedu/duke/Account.java
  src/main/java/seedu/duke/AccountList.java
  src/main/java/seedu/duke/Currency.java
Labels: type.Enhancement

#50 48 printed message for add account should not be divided by 100
  src/main/java/seedu/duke/AccountList.java
  src/main/java/seedu/duke/commands/AddCommand.java
  src/main/java/seedu/duke/commands/BalanceCommand.java
  src/main/java/seedu/duke/commands/WithdrawCommand.java
  src/test/java/seedu/duke/commands/BalanceCommandTest.java
  src/test/java/seedu/duke/commands/WithdrawCommandTest.java
Labels: type.Bug, priority.High, severity.High

#58 Arif khalid update create account error messages
  src/main/java/seedu/duke/commands/CreateAccountCommand.java
  src/main/java/seedu/duke/constants/ErrorMessage.java
  src/test/java/seedu/duke/commands/CreateAccountTest.java
Labels: type.Bug, severity.Medium

#62 Add check for amount being too small for exchange. Shows exchange rat…
  src/main/java/seedu/duke/Forex.java
  src/main/java/seedu/duke/commands/ExchangeCommand.java
  src/main/java/seedu/duke/commands/ShowRateCommand.java
  src/main/java/seedu/duke/constants/ErrorMessage.java
  src/main/java/seedu/duke/exceptions/ExchangeAmountTooSmallException.java
Labels: type.Bug, severity.Medium

#70 Arif khalid update dg
  diagrams/AccountListClassDiagram.drawio
  diagrams/AccountListObjectDiagram1.drawio
  diagrams/AccountListObjectDiagram2.drawio
  diagrams/AccountListObjectDiagram3.drawio
  diagrams/CreateAccountSeqDiagram.drawio
  docs/DeveloperGuide.md
  images/AccountListClassDiagram.png
  images/AccountListObjectDiagram1.png
  images/AccountListObjectDiagram2.png
  images/AccountListObjectDiagram3.png
  images/CreateAccountSeqDiagram.png
Labels: documentation

#72 Developer guide architecture
  docs/DeveloperGuide.md
  docs/diagrams/AccountListClassDiagram.drawio
  docs/diagrams/AccountListObjectDiagram1.drawio
  docs/diagrams/AccountListObjectDiagram2.drawio
  docs/diagrams/AccountListObjectDiagram3.drawio
  docs/diagrams/ArchitectureDiagram.drawio
  docs/diagrams/CreateAccountSeqDiagram.drawio
  docs/diagrams/UiClassDiagram.drawio
  docs/images/AccountListClassDiagram.png
  docs/images/AccountListObjectDiagram1.png
  docs/images/AccountListObjectDiagram2.png
  docs/images/AccountListObjectDiagram3.png
  docs/images/ArchitectureDiagram.png
  docs/images/CreateAccountSeqDiagram.png
  docs/images/UiClassDiagram.png
Labels: documentation

#93 Arif khalid transaction skeleton
  src/main/java/seedu/duke/Transaction.java
  src/main/java/seedu/duke/TransactionManager.java
Labels: type.Enhancement

#95 Arif khalid update transaction class
  src/main/java/seedu/duke/Transaction.java
  src/main/java/seedu/duke/TransactionManager.java
Labels: priority.High

#83 Pull Exchange Rates from Open Exchange Rates API
  build.gradle
  docs/DeveloperGuide.md
  docs/diagrams/APIClassDiagram.drawio
  docs/images/APIClassDiagram.png
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Forex.java
  src/main/java/seedu/duke/api/ExchangeRates.java
  src/main/java/seedu/duke/api/ExchangeRatesApi.java
  src/main/java/seedu/duke/api/ExchangeRatesApiClient.java
  src/main/java/seedu/duke/api/ExchangeRatesResponse.java
  src/main/java/seedu/duke/commands/ShowRateCommand.java
  src/main/java/seedu/duke/constants/ErrorMessage.java
  src/main/java/seedu/duke/constants/Message.java
  src/main/java/seedu/duke/exceptions/IllegalCurrencyException.java
  src/test/java/seedu/duke/commands/ExchangeCommandTest.java
  src/test/java/seedu/duke/commands/ShowRateCommandTest.java
Labels: documentation, type.Task, priority.High

#97 Exchange and show-rate ug documentation
  docs/UserGuide.md
Labels: documentation

#104 Arif khalid transaction list commands
  src/main/java/seedu/duke/Account.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Transaction.java
  src/main/java/seedu/duke/TransactionManager.java
  src/main/java/seedu/duke/commands/CommandType.java
  src/main/java/seedu/duke/commands/ShowRateCommand.java
  src/main/java/seedu/duke/commands/TransactionCommand.java
  src/main/java/seedu/duke/constants/DateConstants.java
  src/main/java/seedu/duke/constants/ErrorMessage.java
  src/main/java/seedu/duke/constants/Message.java
  src/main/java/seedu/duke/constants/TransactionFlag.java
  src/main/java/seedu/duke/exceptions/InvalidSearchTransactionByCurrencyException.java
  src/main/java/seedu/duke/exceptions/InvalidSearchTransactionByDateException.java
  src/main/java/seedu/duke/exceptions/InvalidSearchTransactionByDescException.java
  src/main/java/seedu/duke/exceptions/InvalidSearchTransactionByMonthException.java
  src/main/java/seedu/duke/exceptions/InvalidTransactionFlagException.java
  src/main/java/seedu/duke/exceptions/NoTransactionsOfSearchParameterException.java
  src/main/java/seedu/duke/exceptions/NoTransactionsRecordedException.java
  src/main/java/seedu/duke/parser/Parser.java
  src/test/java/seedu/duke/commands/TransactionCommandTest.java
Labels: type.Enhancement

#99 Gan Zhen Yang Log add command to transaction
  src/main/java/seedu/duke/TransactionManager.java
  src/main/java/seedu/duke/commands/AddCommand.java
  src/test/java/seedu/duke/commands/AddCommandTest.java
Labels: type.Story, priority.High

#103 Delete command delete currency transaction
  src/main/java/seedu/duke/TransactionManager.java
  src/main/java/seedu/duke/commands/DeleteAccountCommand.java
Labels: type.Task, priority.High

#107 Bug fix exchange command
  src/main/java/seedu/duke/commands/ExchangeCommand.java
Labels: type.Bug, severity.VeryLow

#106 Arif khalid update transaction dg and ug, minor bug fix in Transactions
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ShowTransactionsSeqDiagram.drawio
  docs/diagrams/TransactionsClassDiagram.drawio
  docs/images/ShowTransactionsSeqDiagram.png
  docs/images/TransactionsClassDiagram.png
  src/main/java/seedu/duke/Transaction.java
  src/main/java/seedu/duke/constants/ErrorMessage.java
  src/main/java/seedu/duke/constants/Message.java
Labels: documentation

#111 Default rates
  src/main/java/seedu/duke/api/ExchangeRates.java
  src/main/java/seedu/duke/constants/ErrorMessage.java
Labels: type.Bug, priority.Medium

#112 Update ug
  docs/UserGuide.md
  src/main/java/seedu/duke/constants/Message.java
Labels: documentation

#113 Bug fix decimal rounding
  src/main/java/seedu/duke/commands/ExchangeCommand.java
  src/test/java/seedu/duke/commands/ExchangeCommandTest.java
Labels: type.Bug, severity.High

#115 Add the ability to write to file.
  .gitignore
  src/main/java/seedu/duke/Account.java
  src/main/java/seedu/duke/AccountList.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/TransactionManager.java
  src/main/java/seedu/duke/api/ExchangeRates.java
  src/main/java/seedu/duke/commands/AddCommand.java
  src/main/java/seedu/duke/commands/ExchangeCommand.java
  src/main/java/seedu/duke/commands/WithdrawCommand.java
  src/main/java/seedu/duke/storage/LocalDateTimeAdapter.java
  src/main/java/seedu/duke/storage/Store.java
  src/main/java/seedu/duke/storage/StoreInterface.java
  src/main/java/seedu/duke/storage/TestStore.java
  src/test/java/seedu/duke/commands/AddCommandTest.java
  src/test/java/seedu/duke/commands/BalanceCommandTest.java
  src/test/java/seedu/duke/commands/CreateAccountTest.java
  src/test/java/seedu/duke/commands/DeleteAccountCommandTest.java
  src/test/java/seedu/duke/commands/ShowRateCommandTest.java
  src/test/java/seedu/duke/commands/TransactionCommandTest.java
  src/test/java/seedu/duke/commands/WithdrawCommandTest.java
Labels: type.Enhancement, priority.High
