Repository AY2223S2-CS2113-T13-1/tp, pull requests merged in 2023-04, with the labels that each got.

#178 Fix the exit command not immediately terminating the program
  src/main/java/seedu/duke/Duke.java
Labels: type.Bug, severity.Medium

#182 Wrong withdraw comannd exception desc
  src/main/java/seedu/duke/commands/WithdrawCommand.java
  src/main/java/seedu/duke/constants/ErrorMessage.java
  src/main/java/seedu/duke/exceptions/InvalidWithdrawAmountException.java
Labels: type.Bug, severity.Medium

#184 Show rate ped
  docs/UserGuide.md
  src/main/java/seedu/duke/api/ExchangeRates.java
  src/main/java/seedu/duke/commands/ShowRateCommand.java
  src/main/java/seedu/duke/constants/ErrorMessage.java
  src/main/java/seedu/duke/constants/Message.java
  src/test/java/seedu/duke/commands/ExchangeCommandTest.java
  src/test/java/seedu/duke/commands/ShowRateCommandTest.java
Labels: type.Enhancement, priority.Medium

#188 Arif khalid fix pe dry run issues
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/TransactionManager.java
  src/main/java/seedu/duke/commands/AddCommand.java
  src/main/java/seedu/duke/commands/Command.java
  src/main/java/seedu/duke/commands/ExchangeCommand.java
  src/main/java/seedu/duke/commands/WithdrawCommand.java
  src/main/java/seedu/duke/constants/DateConstants.java
  src/main/java/seedu/duke/constants/ErrorMessage.java
  src/main/java/seedu/duke/exceptions/AmountTooPreciseException.java
Labels: priority.High, severity.Medium

#185 Exchange cmd ped
  src/main/java/seedu/duke/commands/ExchangeCommand.java
  src/main/java/seedu/duke/constants/ErrorMessage.java
Labels: type.Enhancement, priority.Low

#190 Arif Khalid PPP
  docs/AboutUs.md
  docs/images/Arif-Photo.jpg
  docs/team/arif-khalid.md
Labels: documentation

#183 Limit description 100char
  src/main/java/seedu/duke/commands/AddCommand.java
  src/main/java/seedu/duke/commands/WithdrawCommand.java
  src/main/java/seedu/duke/constants/ErrorMessage.java
  src/main/java/seedu/duke/exceptions/DescriptionTooLongException.java
Labels: type.Enhancement, priority.Low

#177 Update ug PED
  docs/UserGuide.md
  src/main/java/seedu/duke/constants/ErrorMessage.java
Labels: documentation

#194 Arif khalid fix error in ug
  docs/UserGuide.md
Labels: documentation, priority.Medium, severity.VeryLow

#192 Jacob stein ppp
  docs/AboutUs.md
  docs/images/Jacob-Stein.jpg
  docs/team/jacob-stein1.md
Labels: documentation, priority.Low

#200 Implement validator
  src/main/java/seedu/duke/commands/ExchangeCommand.java
  src/main/java/seedu/duke/commands/ShowRateCommand.java
  src/test/java/seedu/duke/commands/ExchangeCommandTest.java
  src/test/java/seedu/duke/commands/ShowRateCommandTest.java
Labels: type.Enhancement, priority.Medium

#201 Update ug ped
  docs/UserGuide.md
  src/main/java/com/moneymoover/constants/Message.java
Labels: documentation

#203 Gan zhen yang ppp
  docs/AboutUs.md
  docs/images/Gan-Zhen-Yang.jpg
  docs/team/gan868611.md
  docs/team/johndoe.md
Labels: documentation

#195 119 program crashes if the json files are corrupted
  docs/UserGuide.md
  src/main/java/com/moneymoover/Account.java
  src/main/java/com/moneymoover/MoneyMoover.java
  src/main/java/com/moneymoover/commands/CommandType.java
  src/main/java/com/moneymoover/constants/ErrorMessage.java
  src/main/java/com/moneymoover/constants/Message.java
  src/main/java/com/moneymoover/parser/Parser.java
  src/main/java/com/moneymoover/storage/Store.java
  src/main/java/com/moneymoover/validator/Validator.java
  src/main/java/seedu/duke/exceptions/AccountNotEmptyException.java
  src/main/java/seedu/duke/exceptions/InvalidShowrateArgumentException.java
  src/main/java/seedu/duke/exceptions/InvalidWithdrawCommandException.java
  src/main/java/seedu/duke/exceptions/NotEnoughInAccountException.java
Labels: type.Bug, documentation, severity.High

#205 Add section on currency and date related inputs to the UG
  docs/UserGuide.md
Labels: documentation

#210 Remove files in wrong directory
  src/main/java/seedu/duke/exceptions/AccountNotEmptyException.java
  src/main/java/seedu/duke/exceptions/InvalidShowrateArgumentException.java
  src/main/java/seedu/duke/exceptions/InvalidWithdrawCommandException.java
  src/main/java/seedu/duke/exceptions/NotEnoughInAccountException.java
Labels: priority.Medium

#214 Remove exchange between same currency
  src/main/java/com/moneymoover/api/ExchangeRates.java
  src/main/java/com/moneymoover/commands/ExchangeCommand.java
  src/main/java/com/moneymoover/commands/ShowRateCommand.java
  src/main/java/com/moneymoover/constants/ErrorMessage.java
  src/main/java/com/moneymoover/exceptions/AccountNotEmptyException.java
  src/main/java/com/moneymoover/exceptions/DescriptionTooLongException.java
  src/main/java/com/moneymoover/exceptions/ExchangeAmountTooSmallException.java
  src/main/java/com/moneymoover/exceptions/ExchangeSameCurrencyException.java
  src/main/java/com/moneymoover/exceptions/InvalidAddCommandException.java
  src/main/java/com/moneymoover/exceptions/InvalidAmountToAddException.java
  src/main/java/com/moneymoover/exceptions/InvalidBigDecimalException.java
  src/main/java/com/moneymoover/exceptions/InvalidDeleteAccountCommandException.java
  src/main/java/com/moneymoover/exceptions/InvalidSearchTransactionByCurrencyException.java
  src/main/java/com/moneymoover/exceptions/InvalidSearchTransactionByDateException.java
  src/main/java/com/moneymoover/exceptions/InvalidSearchTransactionByDescException.java
  src/main/java/com/moneymoover/exceptions/InvalidSearchTransactionByMonthException.java
  src/main/java/com/moneymoover/exceptions/InvalidTransactionFlagException.java
  src/main/java/com/moneymoover/exceptions/InvalidUpdateBalanceActionException.java
  src/main/java/com/moneymoover/exceptions/InvalidWithdrawAmountException.java
  src/main/java/com/moneymoover/exceptions/InvalidWithdrawCommandException.java
  src/main/java/com/moneymoover/exceptions/NoTransactionsOfSearchParameterException.java
  src/main/java/com/moneymoover/exceptions/TooLargeAmountException.java
  src/test/java/com/moneymoover/commands/ExchangeCommandTest.java
Labels: type.Enhancement

#217 Minimum exchange target
  docs/UserGuide.md
  src/main/java/com/moneymoover/api/ExchangeRates.java
  src/main/java/com/moneymoover/commands/ExchangeCommand.java
  src/main/java/com/moneymoover/constants/ErrorMessage.java
  src/main/java/com/moneymoover/exceptions/ConvertedAmountTooSmallException.java
  src/main/java/com/moneymoover/validator/Validator.java
  src/test/java/com/moneymoover/commands/ExchangeCommandTest.java
Labels: type.Bug, priority.Medium

#216 Manual testing instructions
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/bawfen.md
  src/main/java/com/moneymoover/Account.java
  src/main/java/com/moneymoover/AccountList.java
  src/main/java/com/moneymoover/api/ExchangeRates.java
  src/main/java/com/moneymoover/commands/ExchangeCommand.java
  src/main/java/com/moneymoover/storage/Store.java
Labels: documentation

#226 Arif khalid standardise documentation in UG
  docs/UserGuide.md
Labels: documentation, priority.Medium, severity.Low

#227 Update dg
  docs/DeveloperGuide.md
  docs/diagrams/AddCommandSeqDiagram.drawio
  docs/diagrams/CreateAccountSeqDiagram.drawio
  docs/diagrams/DeleteAccountCommandSeqDiagram.drawio
  docs/diagrams/ExchangeSeqDiagram.drawio
  docs/diagrams/WithdrawCommandSeqDiagram.drawio
  docs/images/AddCommandSeqDiagram.png
  docs/images/BalanceSeqDiagram.png
  docs/images/CreateAccountSeqDiagram.png
  docs/images/DeleteAccountCommandSeqDiagram.png
  docs/images/ExchangeSeqDiagram.png
  docs/images/WithdrawCommandSeqDiagram.png
Labels: documentation

#234 Add storage to dg
  docs/DeveloperGuide.md
  docs/diagrams/BasicSequence.drawio
  docs/diagrams/ShowTransactionsSeqDiagram.drawio
  docs/diagrams/StoreClassDiagram.drawio
  docs/images/BasicSequence.png
  docs/images/ShowTransactionsSeqDiagram.png
  docs/images/StoreClassDiagram.png
  docs/team/bawfen.md
Labels: documentation, priority.High
